FROM oven/bun:1

WORKDIR /app

ARG DATABASE_URL

# Install OpenSSL for Prisma
RUN apt-get update -y && apt-get install -y openssl

COPY ./packages ./packages
COPY ./bun.lock ./bun.lock

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN bun install 

COPY . .

EXPOSE 3000

CMD ["bun", "run", "start:frontend"]