name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: rosibes/app-backend:${{ github.sha }}
      - name: Deploy to the VM
        run: | 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          mkdir -p /home/runner/.ssh
          ls /home/runner/ssh
          chmod 700 /home/runner/ssh_keygen
          ssh -o StrictHostKeyChecking=no -i ~/ssh_keygen ubuntu@18.234.144.102 -t "docker stop app_backend && docker run --name user_backend -d -p 8080:8080 rosibes/app-backend:${{ github.sha }}"