name: Deploy the backend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.backend
          push: true
          tags: rosibes/app-backend:${{ github.sha }}
      - name: Deploy to the Virtual Machine
        run: | 
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@18.234.144.102 "
            docker network create app-network || true &&
            docker stop postgres || true && docker rm postgres || true &&
            docker run --name postgres --network app-network -d -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword postgres:15 &&
            sleep 5 &&
            docker stop app_backend || true && docker rm app_backend || true &&
            docker run --name app_backend --network app-network -d -p 8080:8080 -e DATABASE_URL='postgresql://postgres:mysecretpassword@postgres:5432/postgres' rosibes/app-backend:${{ github.sha }} &&
            sleep 5 &&
            docker exec app_backend bun run db:migrate
          "