name: Deploy the frontend
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      
      - name: Docker login
        uses: docker/login-action@v2
        with: 
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.frontend
          push: true
          tags: rosibes/app-frontend:${{ github.sha }}
      - name: Deploy to Virtual Machinee
        run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
          chmod 600 ~/ssh_key
          ssh -o StrictHostKeyChecking=no -i ~/ssh_key ubuntu@18.234.144.102 "
            docker network create app-network || true &&
            if ! docker ps | grep -q postgres; then
              docker run --name postgres --network app-network -d -p 5432:5432 -e POSTGRES_PASSWORD=mysecretpassword postgres:15
              sleep 10
            fi &&
            docker stop app_fe || true && docker rm app_fe || true &&
            docker run --name app_fe --network app-network -d -p 3000:3000 -e DATABASE_URL='postgresql://postgres:mysecretpassword@postgres:5432/postgres' -e HOSTNAME='0.0.0.0' rosibes/app-frontend:${{ github.sha }}
          "